# Generated by Django 2.0.2 on 2018-11-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
